services:
  - type: web
    name: sistema-acai-server
    runtime: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
